[target.aarch64-unknown-linux-musl]
linker = "aarch64-linux-musl-gcc"
# target-cpu=native for our benchmarking
# force-frame-pointers=yes for our benchmarking
rustflags = [
  "-C",
  "target-feature=-crt-static",
  "-Ctarget-cpu=native",
  "-Cforce-frame-pointers=yes",
]

[target.x86_64-unknown-linux-gnu]
rustflags = ["-Ctarget-cpu=native", "-Cforce-frame-pointers=yes"]
